### ISSUE TITLE
[support request] Support large file preview

### ISSUE THREAD

**Issue by Cyberhan123** [hyrious/npm-browser#3]

**Comment by hyrious** [comment]
We could turn the Editor.vue into using a real editor (like codemirror) to make that.

**Comment by Cyberhan123** [comment]
> We could turn the Editor.vue into using a real editor (like codemirror) to make that.

I'd like to help

**Comment by hyrious** [comment]
PRs are welcome 👍

**Comment by hyrious** [comment]
I have made one 🤔

**Comment by Cyberhan123** [comment]
> I have made one 🤔

oh,you are too fast
